load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
	name = "protos",
	protos = [
		"device.proto",
		"register.proto"],
	verbose = 1,
	visibility = ["//visibility:public"]
)
